ocadotechnology/codeforlife-portal-backend

.env
package-lock.json
package.json
src/app/theme.ts
src/components/Introduction.tsx
src/components/PageBanner.tsx
src/components/PageSection.tsx
src/components/TabBar.tsx
src/features/footer/Footer.tsx
src/pages/aboutUs/AboutUs.tsx
src/pages/aboutUs/Dedication.tsx
src/pages/codingClubs/ClubAim.tsx
src/pages/codingClubs/CodingClubs.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/5)

fix: CodingClub page

---

.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/50)

Specify backend dir for migration step

---

backend/Pipfile
backend/Pipfile.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/51)

remove google-python-cloud-debugger

---

backend/Pipfile
backend/Pipfile.lock
backend/service/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/52)

add whitenoise for file hosting

---

frontend/package.json
frontend/src/pages/login/Teacher2faBackupForm.tsx
frontend/src/pages/login/Teacher2faForm.tsx
frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx
frontend/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/56)

fix buttons and tables

---

frontend/package.json
frontend/src/pages/login/Teacher2faBackupForm.tsx
frontend/src/pages/login/Teacher2faForm.tsx
frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx
frontend/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/57)

fix buttons and tables (#56)

---

frontend/package.json
frontend/src/pages/login/Teacher2faBackupForm.tsx
frontend/src/pages/login/Teacher2faForm.tsx
frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx
frontend/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/60)

fix migrations issue

---

frontend/package.json
frontend/src/features/header/summary/Summary.tsx
frontend/src/pages/emailVerification/EmailVerification.tsx
frontend/src/pages/home/Home.tsx
frontend/src/pages/home/Quotes.tsx
frontend/src/pages/home/TargetAudience.tsx
frontend/src/pages/resetPassword/ResetPassword.tsx
frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx
frontend/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/62)

home page feedback

---

frontend/src/pages/privacyNotice/ForAdults/Cookies.tsx
frontend/src/pages/privacyNotice/ForAdults/HowToComplain.tsx
frontend/src/pages/privacyNotice/ForAdults/InfoSecurity.tsx
frontend/src/pages/privacyNotice/ForAdults/SharingInfo.tsx
frontend/src/pages/privacyNotice/ForChildren/Cookies.tsx
frontend/src/pages/privacyNotice/ForChildren/HowToComplain.tsx
frontend/src/pages/privacyNotice/ForChildren/WhoWeShareInfoWith.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/70)

fix: add target='_blank' to Links

---

frontend/src/pages/privacyNotice/ForAdults/Cookies.tsx
frontend/src/pages/privacyNotice/ForAdults/HowToComplain.tsx
frontend/src/pages/privacyNotice/ForAdults/InfoSecurity.tsx
frontend/src/pages/privacyNotice/ForAdults/SharingInfo.tsx
frontend/src/pages/privacyNotice/ForChildren/Cookies.tsx
frontend/src/pages/privacyNotice/ForChildren/HowToComplain.tsx
frontend/src/pages/privacyNotice/ForChildren/WhoWeShareInfoWith.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/72)

add target='_blank' to Links (#70)

---

frontend/package.json
frontend/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/74)

update cfl package

---

frontend/src/features/footer/Footer.tsx
frontend/src/features/footer/Logos.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/75)

fix: spacing and logo sizes

---

frontend/package.json
frontend/src/components/CflTable.tsx
frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx
frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx
frontend/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/80)

fix: new portal edits - table greys

---

backend/Pipfile
backend/Pipfile.lock
frontend/src/features/header/summary/Summary.tsx
frontend/src/features/header/user/Unauthenticated.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/102)

fix: New portal edits - Header

---

.github/workflows/main.yml
backend/.gcloudignore
backend/Pipfile
backend/Pipfile.lock
backend/app.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/103)

Fix pipeline

---

frontend/src/pages/register/BaseForm.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/112)

fix: new portal edits - /register

---

backend/portal/forms/admin.py
backend/portal/urls/admin.py
backend/portal/views/admin.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/115)

feat: admin views

---

backend/portal/urls/api.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/118)

feat: 19 api views

---

backend/service/production_settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/121)

fix: add self as a media source

---

frontend/src/pages/student/Kurono.tsx
frontend/src/pages/student/RapidRouter.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/120)

fix: 91 new portal edits student 

---

frontend/src/components/CflTable.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/117)

fix: table row grey

---

frontend/src/features/deleteAccountForm/DeleteAccountForm.tsx
frontend/src/pages/teacherDashboard/account/YourAccount.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/123)

fix: 93 new portal edits teacherdashboardaccount

---

frontend/src/components/form/StudentNameField.tsx
frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/125)

fix: New portal edits - student release page

---

backend/service/production_settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/124)

fix: modify domain()

---

frontend/src/components/CopyToClipboardIcon.tsx
frontend/src/features/newStudentsTable/NewStudentsTable.tsx
frontend/src/pages/teacherDashboard/classes/Classes.tsx
frontend/src/pages/teacherDashboard/classes/editClass/student/resetStudent/ResetStudent.tsx

The gray colours seem to be okay
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/127)

fix: added spacings and the copy to clipboard functionality 

---

backend/service/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/131)

fix: copy csp settings to settings.py

---

backend/service/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/132)

fix: tweak domain function

---

frontend/src/components/form/CflForm.tsx
frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/129)

fix: fix padding

---

backend/service/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/135)

fix: modify settings.py according to github action yml

---

.github/workflows/main.yml
backend/app.yaml
backend/service/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/136)

fix: add MODULE_NAME into app.yaml

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/137)

include repo introduction and environment urls

---

frontend/src/pages/login/Teacher2faBackupForm.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/149)

fix: changed the header from 'Welcome' to 'Log in as a teacher'

---

frontend/.env
frontend/src/pages/home/AboutUs.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/154)

fix: missing link in homepage

---

backend/portal/tests/views/cron/test_user.py
backend/portal/views/cron/user.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/168)

fix: Update URLs in cron jobs

---

frontend/src/pages/teacher/TeacherSlides.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/170)

fix: increase slide interval time

---

.github/workflows/main.yml
backend/app.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/171)

Load env vars

---

frontend/package.json
frontend/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/172)

fix: update js package to 1.27.1

---

backend/portal/urls/teacher/dashboard.py
backend/portal/views/teacher/dashboard.py
frontend/src/app/api/teacher/dashboard.ts
frontend/src/app/api/teacher/dashboardClasses.ts
frontend/src/app/router/paths.ts
frontend/src/app/router/routes/teacher.tsx
frontend/src/app/schemas.ts
frontend/src/pages/login/Login.tsx
frontend/src/pages/teacherDashboard/TeacherDashboard.tsx
frontend/src/pages/teacherDashboard/YourSchool.tsx
frontend/src/pages/teacherDashboard/classes/AddExternalStudent.tsx
frontend/src/pages/teacherDashboard/classes/AddedExternalStudent.tsx
frontend/src/pages/teacherDashboard/classes/Classes.tsx
frontend/src/pages/teacherDashboard/classes/MoveClasses.tsx
frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/180)

feat: teacher views classes dashboard

---

.vscode/tasks.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/182)

add service_name

---

backend/portal/urls/teacher/dashboard.py
backend/portal/views/teacher/dashboard.py
frontend/src/app/api/index.ts
frontend/src/app/api/teacher/teach.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184)

feat: adding get-students-endpoint

---

backend/portal/urls/teacher/teach.py
backend/portal/views/teacher/teach.py
frontend/src/app/api/index.ts
frontend/src/app/api/teacher/teach.ts
frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/183)

feat: teacher teach delete class

---

.github/workflows/main.yml
CONTRIBUTING.md
LICENSE.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/197)

docs: license and contributing

---

backend/service/urls.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/249)

include aimmo urls

---

backend/service/settings.py
backend/service/urls.py
run

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/250)

Serve Rapid Router

---

backend/service/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/252)

enable atomic requests

---

backend/api/tests/views/test_school.py
backend/api/views/school.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/261)

Test school update

---

backend/Pipfile
backend/Pipfile.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/298)

fix: install cfl package dev extra

---

.github/workflows/main.yml
backend/Pipfile
backend/Pipfile.lock
backend/api/fixtures/school_1.json
backend/api/models/__init__.py
backend/api/serializers/__init__.py
backend/api/serializers/school_teacher_invitation.py
backend/api/serializers/user.py
backend/api/signals/school_teacher_invitation.py
backend/api/tests/serializers/test_school_teacher_invitation.py
backend/api/tests/serializers/test_user.py
backend/api/tests/signals/test_school_teacher_invitation.py
backend/api/tests/views/test_school_teacher_invitation.py
backend/api/tests/views/test_user.py
backend/api/urls.py
backend/api/views/__init__.py
backend/api/views/school_teacher_invitation.py
backend/api/views/user.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264)

Invite teacher

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/299)

Add licence info to Readme

---

backend/Pipfile
backend/Pipfile.lock
backend/api/tests/views/test_klass.py
backend/api/tests/views/test_school.py
backend/api/tests/views/test_school_teacher_invitation.py
backend/api/tests/views/test_user.py
backend/api/views/klass.py
backend/api/views/school.py
backend/api/views/school_teacher_invitation.py
backend/api/views/user.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/300)

Bulk anon students

---

backend/api/tests/views/test_auth_factor.py
backend/api/views/auth_factor.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/316)

allow admin teachers to target other teachers in their school

---

backend/Pipfile
backend/Pipfile.lock
backend/api/models/__init__.py
backend/api/models/school_teacher_invitation.py
backend/rapid_router/filters/level.py
backend/rapid_router/models/user.py
backend/rapid_router/serializers/level.py
backend/service/settings.py
backend/service/urls.py
backend/sso/forms.py
backend/sso/tests/test_views.py
backend/sso/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/322)

fix static type hint errors

---

.github/workflows/main.yml
Pipfile
Pipfile.lock
scripts/hard-install
settings.py
src/urls.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/353)

add source path

---

settings.py
src/api/signals/student.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356)

Send request accepted campaign to student in signal

---

Pipfile
Pipfile.lock
src/api/serializers/school_teacher_invitation.py
src/api/signals/school_teacher_invitation.py
src/sso/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/359)

Portal frontend19

---

Pipfile
Pipfile.lock
settings.py
src/api/serializers/auth_factor.py
src/api/serializers/auth_factor_test.py
src/api/serializers/teacher.py
src/api/serializers/user.py
src/api/serializers/user_test.py
src/api/views/klass.py
src/api/views/klass_test.py
src/api/views/school_teacher_invitation.py
src/api/views/user.py
src/api/views/user_test.py
src/sso/forms.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/362)

Upgrade to Python 3.12

---

Pipfile
Pipfile.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/366)

new cfl package

---

src/api/serializers/school.py
src/api/serializers/school_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/377)

fix: create school

---

Pipfile
Pipfile.lock
src/api/serializers/auth_factor.py
src/api/serializers/auth_factor_test.py
src/api/views/auth_factor.py
src/api/views/auth_factor_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/388)

fix: otp flow

---

Pipfile
Pipfile.lock
application.py
src/urls.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/401)

fix: Install latest package
